item {
    id: 1
    name: 'Apple'
}

item {
    id: 2
    name: 'Apricot'
}

item {
    id: 3
    name: 'Avocado'
}

item {
    id: 4
    name: 'Banana'
}

item {
    id: 5
    name: 'Beetroot'
}

item {
    id: 6
    name: 'Blueberry'
}

item {
    id: 7
    name: 'Cactus'
}

item {
    id: 8
    name: 'Cantaloupe'
}

item {
    id: 9
    name: 'Carambula'
}

item {
    id: 10
    name: 'Cauliflower'
}

item {
    id: 11
    name: 'Cherry'
}

item {
    id: 12
    name: 'Chestnut'
}

item {
    id: 13
    name: 'Clementine'
}

item {
    id: 14
    name: 'Cocos'
}

item {
    id: 15
    name: 'Dates'
}

item {
    id: 16
    name: 'Eggplant'
}

item {
    id: 17
    name: 'Ginger'
}

item {
    id: 18
    name: 'Granadilla'
}

item {
    id: 19
    name: 'Grape'
}

item {
    id: 20
    name: 'Grapefruit'
}

item {
    id: 21
    name: 'Guava'
}

item {
    id: 22
    name: 'Hazelnut'
}

item {
    id: 23
    name: 'Huckleberry'
}

item {
    id: 24
    name: 'Kaki'
}

item {
    id: 25
    name: 'Kiwi'
}

item {
    id: 26
    name: 'Kohlrabi'
}

item {
    id: 27
    name: 'Kumquats'
}

item {
    id: 28
    name: 'Lemon'
}

item {
    id: 29
    name: 'Limes'
}

item {
    id: 30
    name: 'Lychee'
}

item {
    id: 31
    name: 'Mandarine'
}

item {
    id: 32
    name: 'Mango'
}

item {
    id: 33
    name: 'Mangostan'
}

item {
    id: 34
    name: 'Maracuja'
}

item {
    id: 35
    name: 'Melon'
}

item {
    id: 36
    name: 'Mulberry'
}

item {
    id: 37
    name: 'Nectarine'
}

item {
    id: 38
    name: 'Nut'
}

item {
    id: 39
    name: 'Onion'
}

item {
    id: 40
    name: 'Orange'
}

item {
    id: 41
    name: 'Papaya'
}

item {
    id: 42
    name: 'Passion'
}

item {
    id: 43
    name: 'Peach'
}

item {
    id: 44
    name: 'Pear'
}

item {
    id: 45
    name: 'Pepino'
}

item {
    id: 46
    name: 'Pepper'
}

item {
    id: 47
    name: 'Physalis'
}

item {
    id: 48
    name: 'Pineapple'
}

item {
    id: 49
    name: 'Pitahaya'
}

item {
    id: 50
    name: 'Plum'
}

item {
    id: 51
    name: 'Pomegranate'
}

item {
    id: 52
    name: 'Pomelo'
}

item {
    id: 53
    name: 'Potato'
}

item {
    id: 54
    name: 'Quince'
}

item {
    id: 55
    name: 'Rambutan'
}

item {
    id: 56
    name: 'Raspberry'
}

item {
    id: 57
    name: 'Redcurrant'
}

item {
    id: 58
    name: 'Salak'
}

item {
    id: 59
    name: 'Strawberry'
}

item {
    id: 60
    name: 'Tamarillo'
}

item {
    id: 61
    name: 'Tangelo'
}

item {
    id: 62
    name: 'Tomato'
}

item {
    id: 63
    name: 'Walnut'
}